//Name : Moe Myat Thwe
//Name: Moe Myat Thwe
//Admin no: P2340362
//Class : DIT/FT/2B/23

package jprg_ca_2ndtry;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;




public class UserView extends javax.swing.JFrame {

    private StudentController controller;
    private StudentManagementView mainView;
    
//    public UserView() {
//        initComponents();
//        SoundPlayer.playSound("backgroundsound.wav");
//        controller = new StudentController(this);
//    }
    
    public UserView(StudentManagementView mainView) {
        this.mainView = mainView;
        initComponents();
        addLogoutButtonListener();
        SoundPlayer.playSound("backgroundsound.wav");
        controller = new StudentController(this);
    }

    private void addLogoutButtonListener() {
        jButtonLogOut.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleLogout();
            }
        });
    }

    private void handleLogout() {
        this.setVisible(false);
        mainView.setVisible(true);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jTabbedPaneForStudentAndModuleInfo = new javax.swing.JTabbedPane();
        UserMainPanel = new javax.swing.JPanel();
        PanelForStudentInfoView = new javax.swing.JPanel();
        LabelForStudentName = new javax.swing.JLabel();
        LabelForAdmin = new javax.swing.JLabel();
        labelForClassNo = new javax.swing.JLabel();
        labelForGPA = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        admin = new javax.swing.JTextField();
        classNo = new javax.swing.JTextField();
        gpa = new javax.swing.JTextField();
        studentInfoNEXTButton = new java.awt.Button();
        studentInfoPREVButton = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        getSearchStudentByOrderNumberButton = new javax.swing.JButton();
        totalStudentsLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchStudentByOrderNum = new javax.swing.JTextField();
        PanelForStudentModuleView = new javax.swing.JPanel();
        labelForModCode = new javax.swing.JLabel();
        labelForModName = new javax.swing.JLabel();
        Marks = new javax.swing.JLabel();
        labelForCredit = new javax.swing.JLabel();
        labelForGrade = new javax.swing.JLabel();
        modCode = new javax.swing.JTextField();
        modName = new javax.swing.JTextField();
        marks = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        studentModuleNEXTButton = new java.awt.Button();
        studentModulePREVbutton = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        SearchModuleByOrderNum = new javax.swing.JTextField();
        totalModulesLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        getSearchModuleByOrderNumberButton = new javax.swing.JButton();
        ButtonForExit = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        SearchPanel = new javax.swing.JPanel();
        MainSearchPane = new javax.swing.JPanel();
        PanelForSearch = new javax.swing.JPanel();
        LabelForSearch = new javax.swing.JLabel();
        RadioButtonForSearchByClass = new javax.swing.JRadioButton();
        RadioButtonForSearchByName = new javax.swing.JRadioButton();
        TextFieldForSearch = new javax.swing.JTextField();
        ButtonForSearch = new javax.swing.JButton();
        MainPanelForSearchResult = new javax.swing.JPanel();
        jScrollPaneForResult = new javax.swing.JScrollPane();
        PanelForSearchResult = new javax.swing.JTextPane();
        LabelForResult = new javax.swing.JLabel();
        jPanelForTopStudentTable = new javax.swing.JPanel();
        jScrollPaneForTopStudentInEachClass = new javax.swing.JScrollPane();
        TableForOutstandingSturentsResult = new javax.swing.JTable();
        JComboBoxForChoosingClass = new javax.swing.JComboBox<>();
        jLabelforOutstandingStudentsInEachClass = new javax.swing.JLabel();
        SearchButtonForOutstandingStudent = new javax.swing.JButton();
        jPanelStudentPerfomanceForEachModule = new javax.swing.JPanel();
        chartPanelContainer = new javax.swing.JPanel();
        displayChartButton = new javax.swing.JButton();
        jScrollPaneForModulePerformanceRank = new javax.swing.JScrollPane();
        jTextAreaShowingModulePerformanceRank = new javax.swing.JTextArea();
        FilterPanel = new javax.swing.JPanel();
        jSplitPaneForSearchByFilteringNumofMod = new javax.swing.JSplitPane();
        jPanelForChoosingNumOfModules = new javax.swing.JPanel();
        CheckBoxMorethan5Modules = new javax.swing.JCheckBox();
        CheckBox5Modules = new javax.swing.JCheckBox();
        CheckBox4Modules = new javax.swing.JCheckBox();
        CheckBox3Modules = new javax.swing.JCheckBox();
        CheckBox2Modules = new javax.swing.JCheckBox();
        CheckBox1Module = new javax.swing.JCheckBox();
        CheckBoxNoModule = new javax.swing.JCheckBox();
        jToggleButtonSearch = new javax.swing.JToggleButton();
        jPanelForResultByFilteringModule = new javax.swing.JPanel();
        jScrollPaneResultOfFilteringNumOfModules = new javax.swing.JScrollPane();
        jListForResultFilteringNumOfModules = new javax.swing.JList<>();
        jLabelStudentList = new javax.swing.JLabel();
        jProgressBarForFilteringModule = new javax.swing.JProgressBar();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1125, 810));

        jTabbedPaneForStudentAndModuleInfo.setBackground(new java.awt.Color(249, 239, 248));
        jTabbedPaneForStudentAndModuleInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        jTabbedPaneForStudentAndModuleInfo.setForeground(new java.awt.Color(206, 162, 185));
        jTabbedPaneForStudentAndModuleInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPaneForStudentAndModuleInfo.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jTabbedPaneForStudentAndModuleInfo.setPreferredSize(new java.awt.Dimension(1080, 720));

        UserMainPanel.setBackground(new java.awt.Color(249, 239, 248));

        PanelForStudentInfoView.setBackground(new java.awt.Color(249, 239, 248));
        PanelForStudentInfoView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS UI Gothic", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        PanelForStudentInfoView.setForeground(new java.awt.Color(255, 255, 255));
        PanelForStudentInfoView.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        PanelForStudentInfoView.setLayout(new java.awt.GridBagLayout());

        LabelForStudentName.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        LabelForStudentName.setText("Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(LabelForStudentName, gridBagConstraints);

        LabelForAdmin.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        LabelForAdmin.setText("Admin :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(LabelForAdmin, gridBagConstraints);

        labelForClassNo.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        labelForClassNo.setText("Class No :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(labelForClassNo, gridBagConstraints);

        labelForGPA.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        labelForGPA.setText("GPA :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(labelForGPA, gridBagConstraints);

        name.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(name, gridBagConstraints);

        admin.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(admin, gridBagConstraints);

        classNo.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        classNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(classNo, gridBagConstraints);

        gpa.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(gpa, gridBagConstraints);

        studentInfoNEXTButton.setBackground(new java.awt.Color(206, 162, 185));
        studentInfoNEXTButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentInfoNEXTButton.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        studentInfoNEXTButton.setForeground(new java.awt.Color(255, 255, 255));
        studentInfoNEXTButton.setLabel("Next");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 15, 10, 15);
        PanelForStudentInfoView.add(studentInfoNEXTButton, gridBagConstraints);

        studentInfoPREVButton.setBackground(new java.awt.Color(206, 162, 185));
        studentInfoPREVButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentInfoPREVButton.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        studentInfoPREVButton.setForeground(new java.awt.Color(255, 255, 255));
        studentInfoPREVButton.setLabel("Prev");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 15, 10, 15);
        PanelForStudentInfoView.add(studentInfoPREVButton, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Student");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(jLabel2, gridBagConstraints);

        getSearchStudentByOrderNumberButton.setBackground(new java.awt.Color(206, 162, 185));
        getSearchStudentByOrderNumberButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        getSearchStudentByOrderNumberButton.setForeground(new java.awt.Color(255, 255, 255));
        getSearchStudentByOrderNumberButton.setText("Search");
        getSearchStudentByOrderNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSearchStudentByOrderNumberButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(getSearchStudentByOrderNumberButton, gridBagConstraints);

        totalStudentsLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(totalStudentsLabel, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel1.setText("of");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(jLabel1, gridBagConstraints);

        SearchStudentByOrderNum.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        SearchStudentByOrderNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentByOrderNumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentInfoView.add(SearchStudentByOrderNum, gridBagConstraints);

        PanelForStudentModuleView.setBackground(new java.awt.Color(249, 239, 248));
        PanelForStudentModuleView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Module Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS UI Gothic", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        PanelForStudentModuleView.setLayout(new java.awt.GridBagLayout());

        labelForModCode.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        labelForModCode.setText("Mod Code :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(labelForModCode, gridBagConstraints);

        labelForModName.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        labelForModName.setText("Mod Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(labelForModName, gridBagConstraints);

        Marks.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        Marks.setText("Marks :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(Marks, gridBagConstraints);

        labelForCredit.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        labelForCredit.setText("Credit :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(labelForCredit, gridBagConstraints);

        labelForGrade.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        labelForGrade.setText("Grade :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(labelForGrade, gridBagConstraints);

        modCode.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        modCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(modCode, gridBagConstraints);

        modName.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        modName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(modName, gridBagConstraints);

        marks.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(marks, gridBagConstraints);

        credit.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(credit, gridBagConstraints);

        grade.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(grade, gridBagConstraints);

        studentModuleNEXTButton.setBackground(new java.awt.Color(206, 162, 185));
        studentModuleNEXTButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentModuleNEXTButton.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        studentModuleNEXTButton.setForeground(new java.awt.Color(255, 255, 255));
        studentModuleNEXTButton.setLabel("Next");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 15, 10);
        PanelForStudentModuleView.add(studentModuleNEXTButton, gridBagConstraints);

        studentModulePREVbutton.setBackground(new java.awt.Color(206, 162, 185));
        studentModulePREVbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentModulePREVbutton.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        studentModulePREVbutton.setForeground(new java.awt.Color(255, 255, 255));
        studentModulePREVbutton.setLabel("Prev");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 15, 10);
        PanelForStudentModuleView.add(studentModulePREVbutton, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Module");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(jLabel3, gridBagConstraints);

        SearchModuleByOrderNum.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(SearchModuleByOrderNum, gridBagConstraints);

        totalModulesLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(totalModulesLabel, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel4.setText("of");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(jLabel4, gridBagConstraints);

        getSearchModuleByOrderNumberButton.setBackground(new java.awt.Color(206, 162, 185));
        getSearchModuleByOrderNumberButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        getSearchModuleByOrderNumberButton.setForeground(new java.awt.Color(255, 255, 255));
        getSearchModuleByOrderNumberButton.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForStudentModuleView.add(getSearchModuleByOrderNumberButton, gridBagConstraints);

        ButtonForExit.setBackground(new java.awt.Color(206, 162, 185));
        ButtonForExit.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        ButtonForExit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonForExit.setText("♡₊˚Exit ");

        jButtonLogOut.setBackground(new java.awt.Color(206, 162, 185));
        jButtonLogOut.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogOut.setText("Log Out₊✧ ");

        javax.swing.GroupLayout UserMainPanelLayout = new javax.swing.GroupLayout(UserMainPanel);
        UserMainPanel.setLayout(UserMainPanelLayout);
        UserMainPanelLayout.setHorizontalGroup(
            UserMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMainPanelLayout.createSequentialGroup()
                .addGroup(UserMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserMainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelForStudentInfoView, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserMainPanelLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(ButtonForExit)))
                .addGroup(UserMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserMainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(PanelForStudentModuleView, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(UserMainPanelLayout.createSequentialGroup()
                        .addComponent(jButtonLogOut)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        UserMainPanelLayout.setVerticalGroup(
            UserMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(UserMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelForStudentInfoView, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelForStudentModuleView, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(UserMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonForExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        PanelForStudentInfoView.getAccessibleContext().setAccessibleName("");
        PanelForStudentModuleView.getAccessibleContext().setAccessibleName("");

        jTabbedPaneForStudentAndModuleInfo.addTab("⋆.˚ Student & Module Info ˙✧°", UserMainPanel);

        SearchPanel.setBackground(new java.awt.Color(249, 239, 248));

        MainSearchPane.setBackground(new java.awt.Color(249, 239, 248));

        PanelForSearch.setBackground(new java.awt.Color(249, 239, 248));
        PanelForSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelForSearch.setLayout(new java.awt.GridBagLayout());

        LabelForSearch.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        LabelForSearch.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 3.7;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForSearch.add(LabelForSearch, gridBagConstraints);

        RadioButtonForSearchByClass.setBackground(new java.awt.Color(249, 239, 248));
        buttonGroup1.add(RadioButtonForSearchByClass);
        RadioButtonForSearchByClass.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        RadioButtonForSearchByClass.setText("By Class");
        RadioButtonForSearchByClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonForSearchByClassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForSearch.add(RadioButtonForSearchByClass, gridBagConstraints);

        RadioButtonForSearchByName.setBackground(new java.awt.Color(249, 239, 248));
        buttonGroup1.add(RadioButtonForSearchByName);
        RadioButtonForSearchByName.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        RadioButtonForSearchByName.setText("By Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForSearch.add(RadioButtonForSearchByName, gridBagConstraints);

        TextFieldForSearch.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        TextFieldForSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldForSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 181;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForSearch.add(TextFieldForSearch, gridBagConstraints);

        ButtonForSearch.setBackground(new java.awt.Color(206, 162, 185));
        ButtonForSearch.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        ButtonForSearch.setForeground(new java.awt.Color(255, 255, 255));
        ButtonForSearch.setText("Search");
        ButtonForSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonForSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        PanelForSearch.add(ButtonForSearch, gridBagConstraints);

        MainPanelForSearchResult.setBackground(new java.awt.Color(249, 239, 248));

        PanelForSearchResult.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jScrollPaneForResult.setViewportView(PanelForSearchResult);

        LabelForResult.setBackground(new java.awt.Color(249, 239, 248));
        LabelForResult.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        LabelForResult.setText("Results");

        javax.swing.GroupLayout MainPanelForSearchResultLayout = new javax.swing.GroupLayout(MainPanelForSearchResult);
        MainPanelForSearchResult.setLayout(MainPanelForSearchResultLayout);
        MainPanelForSearchResultLayout.setHorizontalGroup(
            MainPanelForSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelForSearchResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelForResult, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(MainPanelForSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelForSearchResultLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneForResult, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MainPanelForSearchResultLayout.setVerticalGroup(
            MainPanelForSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelForSearchResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelForResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelForSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelForSearchResultLayout.createSequentialGroup()
                    .addContainerGap(57, Short.MAX_VALUE)
                    .addComponent(jScrollPaneForResult, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );

        jPanelForTopStudentTable.setBackground(new java.awt.Color(249, 239, 248));

        jScrollPaneForTopStudentInEachClass.setBackground(new java.awt.Color(249, 239, 248));

        TableForOutstandingSturentsResult.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        TableForOutstandingSturentsResult.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        TableForOutstandingSturentsResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Name", "Admin Number", "GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableForOutstandingSturentsResult.setRowHeight(30);
        jScrollPaneForTopStudentInEachClass.setViewportView(TableForOutstandingSturentsResult);

        JComboBoxForChoosingClass.setBackground(new java.awt.Color(249, 239, 248));
        JComboBoxForChoosingClass.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        JComboBoxForChoosingClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JComboBoxForChoosingClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxForChoosingClassActionPerformed(evt);
            }
        });

        jLabelforOutstandingStudentsInEachClass.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabelforOutstandingStudentsInEachClass.setText("Search Outstanding Students In a class : ");

        SearchButtonForOutstandingStudent.setBackground(new java.awt.Color(206, 162, 185));
        SearchButtonForOutstandingStudent.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        SearchButtonForOutstandingStudent.setForeground(new java.awt.Color(255, 255, 255));
        SearchButtonForOutstandingStudent.setText("Search");

        javax.swing.GroupLayout jPanelForTopStudentTableLayout = new javax.swing.GroupLayout(jPanelForTopStudentTable);
        jPanelForTopStudentTable.setLayout(jPanelForTopStudentTableLayout);
        jPanelForTopStudentTableLayout.setHorizontalGroup(
            jPanelForTopStudentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelForTopStudentTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelForTopStudentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneForTopStudentInEachClass)
                    .addGroup(jPanelForTopStudentTableLayout.createSequentialGroup()
                        .addComponent(jLabelforOutstandingStudentsInEachClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JComboBoxForChoosingClass, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButtonForOutstandingStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanelForTopStudentTableLayout.setVerticalGroup(
            jPanelForTopStudentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelForTopStudentTableLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelForTopStudentTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelforOutstandingStudentsInEachClass)
                    .addComponent(JComboBoxForChoosingClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButtonForOutstandingStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneForTopStudentInEachClass, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainSearchPaneLayout = new javax.swing.GroupLayout(MainSearchPane);
        MainSearchPane.setLayout(MainSearchPaneLayout);
        MainSearchPaneLayout.setHorizontalGroup(
            MainSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainSearchPaneLayout.createSequentialGroup()
                .addGroup(MainSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainSearchPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MainPanelForSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelForTopStudentTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainSearchPaneLayout.setVerticalGroup(
            MainSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainSearchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainSearchPaneLayout.createSequentialGroup()
                        .addComponent(PanelForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(MainPanelForSearchResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainSearchPaneLayout.createSequentialGroup()
                        .addComponent(jPanelForTopStudentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainSearchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSearchPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneForStudentAndModuleInfo.addTab("⋆.˚ Search Student Info˙✧°", SearchPanel);

        jPanelStudentPerfomanceForEachModule.setBackground(new java.awt.Color(249, 239, 248));

        chartPanelContainer.setBackground(new java.awt.Color(249, 239, 248));

        displayChartButton.setBackground(new java.awt.Color(206, 162, 185));
        displayChartButton.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        displayChartButton.setForeground(new java.awt.Color(255, 255, 255));
        displayChartButton.setText("Display Module Performance Chart");
        displayChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayChartButtonActionPerformed(evt);
            }
        });

        jScrollPaneForModulePerformanceRank.setBackground(new java.awt.Color(249, 239, 248));

        jTextAreaShowingModulePerformanceRank.setBackground(new java.awt.Color(249, 239, 248));
        jTextAreaShowingModulePerformanceRank.setColumns(20);
        jTextAreaShowingModulePerformanceRank.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jTextAreaShowingModulePerformanceRank.setForeground(new java.awt.Color(206, 162, 185));
        jTextAreaShowingModulePerformanceRank.setRows(5);
        jScrollPaneForModulePerformanceRank.setViewportView(jTextAreaShowingModulePerformanceRank);

        javax.swing.GroupLayout chartPanelContainerLayout = new javax.swing.GroupLayout(chartPanelContainer);
        chartPanelContainer.setLayout(chartPanelContainerLayout);
        chartPanelContainerLayout.setHorizontalGroup(
            chartPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartPanelContainerLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(chartPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chartPanelContainerLayout.createSequentialGroup()
                        .addComponent(jScrollPaneForModulePerformanceRank, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chartPanelContainerLayout.createSequentialGroup()
                        .addComponent(displayChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))))
        );
        chartPanelContainerLayout.setVerticalGroup(
            chartPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chartPanelContainerLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPaneForModulePerformanceRank, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(displayChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanelStudentPerfomanceForEachModuleLayout = new javax.swing.GroupLayout(jPanelStudentPerfomanceForEachModule);
        jPanelStudentPerfomanceForEachModule.setLayout(jPanelStudentPerfomanceForEachModuleLayout);
        jPanelStudentPerfomanceForEachModuleLayout.setHorizontalGroup(
            jPanelStudentPerfomanceForEachModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentPerfomanceForEachModuleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanelStudentPerfomanceForEachModuleLayout.setVerticalGroup(
            jPanelStudentPerfomanceForEachModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentPerfomanceForEachModuleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPaneForStudentAndModuleInfo.addTab("⋆.˚ Module Performance˙✧°", jPanelStudentPerfomanceForEachModule);

        FilterPanel.setBackground(new java.awt.Color(249, 239, 248));

        jSplitPaneForSearchByFilteringNumofMod.setBackground(new java.awt.Color(249, 239, 248));
        jSplitPaneForSearchByFilteringNumofMod.setDividerLocation(400);
        jSplitPaneForSearchByFilteringNumofMod.setDividerSize(10);

        jPanelForChoosingNumOfModules.setBackground(new java.awt.Color(249, 239, 248));
        jPanelForChoosingNumOfModules.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelForChoosingNumOfModules.setLayout(new java.awt.GridBagLayout());

        CheckBoxMorethan5Modules.setBackground(new java.awt.Color(249, 239, 248));
        CheckBoxMorethan5Modules.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBoxMorethan5Modules.setText("More than 5 Modules");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBoxMorethan5Modules, gridBagConstraints);

        CheckBox5Modules.setBackground(new java.awt.Color(249, 239, 248));
        CheckBox5Modules.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBox5Modules.setText("5 Modules");
        CheckBox5Modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox5ModulesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBox5Modules, gridBagConstraints);

        CheckBox4Modules.setBackground(new java.awt.Color(249, 239, 248));
        CheckBox4Modules.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBox4Modules.setText("4 Modules");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBox4Modules, gridBagConstraints);

        CheckBox3Modules.setBackground(new java.awt.Color(249, 239, 248));
        CheckBox3Modules.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBox3Modules.setText("3 Modules");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBox3Modules, gridBagConstraints);

        CheckBox2Modules.setBackground(new java.awt.Color(249, 239, 248));
        CheckBox2Modules.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBox2Modules.setText("2 Modules");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBox2Modules, gridBagConstraints);

        CheckBox1Module.setBackground(new java.awt.Color(249, 239, 248));
        CheckBox1Module.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBox1Module.setText("1 Module");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBox1Module, gridBagConstraints);

        CheckBoxNoModule.setBackground(new java.awt.Color(249, 239, 248));
        CheckBoxNoModule.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        CheckBoxNoModule.setText("No Module");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(CheckBoxNoModule, gridBagConstraints);

        jToggleButtonSearch.setBackground(new java.awt.Color(206, 162, 185));
        jToggleButtonSearch.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jToggleButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonSearch.setText("Search");
        jToggleButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelForChoosingNumOfModules.add(jToggleButtonSearch, gridBagConstraints);

        jSplitPaneForSearchByFilteringNumofMod.setLeftComponent(jPanelForChoosingNumOfModules);

        jPanelForResultByFilteringModule.setBackground(new java.awt.Color(249, 239, 248));

        jScrollPaneResultOfFilteringNumOfModules.setBackground(new java.awt.Color(249, 239, 248));

        jListForResultFilteringNumOfModules.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jListForResultFilteringNumOfModules.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneResultOfFilteringNumOfModules.setViewportView(jListForResultFilteringNumOfModules);

        jLabelStudentList.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabelStudentList.setForeground(new java.awt.Color(206, 162, 185));
        jLabelStudentList.setText("₊✩‧₊˚Student Module List ˚₊✩‧₊ ");

        javax.swing.GroupLayout jPanelForResultByFilteringModuleLayout = new javax.swing.GroupLayout(jPanelForResultByFilteringModule);
        jPanelForResultByFilteringModule.setLayout(jPanelForResultByFilteringModuleLayout);
        jPanelForResultByFilteringModuleLayout.setHorizontalGroup(
            jPanelForResultByFilteringModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForResultByFilteringModuleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResultOfFilteringNumOfModules)
                .addContainerGap())
            .addGroup(jPanelForResultByFilteringModuleLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabelStudentList)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanelForResultByFilteringModuleLayout.setVerticalGroup(
            jPanelForResultByFilteringModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelForResultByFilteringModuleLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelStudentList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneResultOfFilteringNumOfModules, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPaneForSearchByFilteringNumofMod.setRightComponent(jPanelForResultByFilteringModule);

        jProgressBarForFilteringModule.setBackground(new java.awt.Color(206, 162, 185));
        jProgressBarForFilteringModule.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FilterPanelLayout = new javax.swing.GroupLayout(FilterPanel);
        FilterPanel.setLayout(FilterPanelLayout);
        FilterPanelLayout.setHorizontalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneForSearchByFilteringNumofMod, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBarForFilteringModule, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        FilterPanelLayout.setVerticalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneForSearchByFilteringNumofMod, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jProgressBarForFilteringModule, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPaneForStudentAndModuleInfo.addTab("⋆.˚ FilterModule˙✧°", FilterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneForStudentAndModuleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneForStudentAndModuleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayChartButtonActionPerformed
        // TODO add your handling code here:
        controller.displayModulePerformanceChart();
    }//GEN-LAST:event_displayChartButtonActionPerformed

    private void jToggleButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonSearchActionPerformed

    private void CheckBox5ModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox5ModulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox5ModulesActionPerformed

    private void TextFieldForSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldForSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldForSearchActionPerformed

    private void RadioButtonForSearchByClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonForSearchByClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonForSearchByClassActionPerformed

    private void marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksActionPerformed

    private void modNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modNameActionPerformed

    private void modCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modCodeActionPerformed

    private void SearchStudentByOrderNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentByOrderNumActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SearchStudentByOrderNumActionPerformed

    private void getSearchStudentByOrderNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSearchStudentByOrderNumberButtonActionPerformed
        // TODO add your handling code here:
        //        StudentController.getSearchStudentByOrderNumberButtonActionPerformed(evt);
    }//GEN-LAST:event_getSearchStudentByOrderNumberButtonActionPerformed

//
    private void classNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classNoActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void ButtonForSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonForSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonForSearchActionPerformed

    private void JComboBoxForChoosingClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxForChoosingClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxForChoosingClassActionPerformed

    private void filterButtonActionPerformed(ActionEvent evt) {
        controller.filterStudentsByModules();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserView().setVisible(true);
//            }
//        });
//    }

java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                StudentManagementView smView = new StudentManagementView();
                StudentManagementController smController = new StudentManagementController(smView);
                smView.setController(smController);
                smView.setVisible(true);
            }
        });
    }

    // Getter methods to access GUI components
    


public JTextField getNameField() {
    return name;
}

public JTextField getAdminField() {
    return admin;
}

public JTextField getClassNoField() {
    return classNo;
}

public JTextField getGpaField() {
    return gpa;
}

public JTextField getModCodeField() {
    return modCode;
}

public JTextField getModNameField() {
    return modName;
}

public JTextField getMarksField() {
    return marks;
}

public JTextField getCreditField() {
    return credit;
}

public JTextField getGradeField() {
    return grade;
}

public java.awt.Button getStudentInfoNEXTButton() {
    return studentInfoNEXTButton;
}

public java.awt.Button getStudentInfoPREVButton() {
    return studentInfoPREVButton;
}

public java.awt.Button getStudentModuleNEXTButton() {
    return studentModuleNEXTButton;
}

public java.awt.Button getStudentModulePREVButton() {
    return studentModulePREVbutton;
}
/////
public JPanel getPanelForStudentInfoView() {
    return PanelForStudentInfoView;
}

public JPanel getPanelForStudentModuleView() {
    return PanelForStudentModuleView;
}
//////

public JButton getButtonForSearch() {
    return ButtonForSearch;
}

public JButton getButtonForExit() {
    return ButtonForExit;
}

 public JButton getjButtonLogOut() {
        return jButtonLogOut;
    }

 public JTextField getTextFieldForSearch() {
        return TextFieldForSearch;
    }

    public JRadioButton getRadioButtonForSearchByClass() {
        return RadioButtonForSearchByClass;
    }

    public JRadioButton getRadioButtonForSearchByName() {
        return RadioButtonForSearchByName;
    }

    public JTextPane getPanelForSearchResult() {
        return PanelForSearchResult;
    }
    
    public JButton getSearchStudentByOrderNumberButton() {
        return getSearchStudentByOrderNumberButton;
    }
    
    public JButton getSearchModuleByOrderNumberButton() {
        return getSearchModuleByOrderNumberButton;
    }
    
    public JTextField getStudentOrderField() {
        return SearchStudentByOrderNum;
    }
    
    public JTextField getTotalStudentsField() {
        return SearchStudentByOrderNum;
    }
    
    public JTextField getStudentModuleOrderField() {
        return SearchModuleByOrderNum;
    }
    
    //tab3-----
    // Getter methods to access the filter checkboxes
public JCheckBox getCheckBoxMoreThan5Modules() {
    return CheckBoxMorethan5Modules;
}

public JCheckBox getCheckBox5Modules() {
    return CheckBox5Modules;
}

public JCheckBox getCheckBox4Modules() {
    return CheckBox4Modules;
}

public JCheckBox getCheckBox3Modules() {
    return CheckBox3Modules;
}

public JCheckBox getCheckBox2Modules() {
    return CheckBox2Modules;
}

public JCheckBox getCheckBox1Module() {
    return CheckBox1Module;
}

public JCheckBox getCheckBoxNoModule() {
    return CheckBoxNoModule;
}

// Getter method to access the result list
public JList<String> getJListForResultFilteringNumOfModules() {
    return jListForResultFilteringNumOfModules;
}

// Getter method to access the progress bar
public JProgressBar getJProgressBarForFilteringModule() {
    return jProgressBarForFilteringModule;
}

public JToggleButton getToggleButtonSearch() {
        return jToggleButtonSearch;
    }

public JPanel getChartPanelContainer() {
    return chartPanelContainer;
}


    
    //-------------------------

// Update methods for the panel titles and fields
    
    public void updateStudentPanelTitle(int currentStudentIndex, int totalStudents) {
    PanelForStudentInfoView.setBorder(javax.swing.BorderFactory.createTitledBorder("Student " + (currentStudentIndex + 1) + " of " + totalStudents));
}
    public void updateTotalModules(int currentModuleIndex, int totalModules) {
    totalModulesLabel.setText(String.valueOf(totalModules));
    SearchModuleByOrderNum.setText(String.valueOf(currentModuleIndex + 1));
}

    public void updateModulePanelTitle(int currentModuleIndex, int totalModules) {
    PanelForStudentModuleView.setBorder(javax.swing.BorderFactory.createTitledBorder("Module " + (currentModuleIndex + 1) + " of " + totalModules));
}
    public void updateTotalStudents(int totalStudents) {
        totalStudentsLabel.setText(String.valueOf(totalStudents));
    }

    public void updateStudentOrderField(int currentStudentIndex, int totalStudents) {
        SearchStudentByOrderNum.setText(String.valueOf(currentStudentIndex + 1));
        totalStudentsLabel.setText(String.valueOf(totalStudents));
    }
    
    //-----------------Search Outstanding Students-------------------

    public JComboBox<String> getJComboBoxForChoosingClass() {
        return JComboBoxForChoosingClass;
    }

    public void populateClassComboBox(ArrayList<Student> students) {
    Set<String> classes = new HashSet<>();
    for (Student student : students) {
        classes.add(student.getClassName());
    }
    JComboBoxForChoosingClass.removeAllItems();
    for (String className : classes) {
        JComboBoxForChoosingClass.addItem(className);
    }
}

public JTable getTableForOutstandingSturentsResult() {
    return TableForOutstandingSturentsResult;
}

public JButton getSearchButtonForOutstandingStudent() {
    return SearchButtonForOutstandingStudent;
}

public JButton getDisplayChartButton() {
    return displayChartButton;
}

public JTextArea getJTextAreaShowingModulePerformanceRank() {
        return jTextAreaShowingModulePerformanceRank;
    }


//--------------------------------------------------------------

    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonForExit;
    private javax.swing.JButton ButtonForSearch;
    private javax.swing.JCheckBox CheckBox1Module;
    private javax.swing.JCheckBox CheckBox2Modules;
    private javax.swing.JCheckBox CheckBox3Modules;
    private javax.swing.JCheckBox CheckBox4Modules;
    private javax.swing.JCheckBox CheckBox5Modules;
    private javax.swing.JCheckBox CheckBoxMorethan5Modules;
    private javax.swing.JCheckBox CheckBoxNoModule;
    private javax.swing.JPanel FilterPanel;
    private javax.swing.JComboBox<String> JComboBoxForChoosingClass;
    private javax.swing.JLabel LabelForAdmin;
    private javax.swing.JLabel LabelForResult;
    private javax.swing.JLabel LabelForSearch;
    private javax.swing.JLabel LabelForStudentName;
    private javax.swing.JPanel MainPanelForSearchResult;
    private javax.swing.JPanel MainSearchPane;
    private javax.swing.JLabel Marks;
    private javax.swing.JPanel PanelForSearch;
    private javax.swing.JTextPane PanelForSearchResult;
    private javax.swing.JPanel PanelForStudentInfoView;
    private javax.swing.JPanel PanelForStudentModuleView;
    private javax.swing.JRadioButton RadioButtonForSearchByClass;
    private javax.swing.JRadioButton RadioButtonForSearchByName;
    private javax.swing.JButton SearchButtonForOutstandingStudent;
    private javax.swing.JTextField SearchModuleByOrderNum;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JTextField SearchStudentByOrderNum;
    private javax.swing.JTable TableForOutstandingSturentsResult;
    private javax.swing.JTextField TextFieldForSearch;
    private javax.swing.JPanel UserMainPanel;
    private javax.swing.JTextField admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel chartPanelContainer;
    private javax.swing.JTextField classNo;
    private javax.swing.JTextField credit;
    private javax.swing.JButton displayChartButton;
    private javax.swing.JButton getSearchModuleByOrderNumberButton;
    private javax.swing.JButton getSearchStudentByOrderNumberButton;
    private javax.swing.JTextField gpa;
    private javax.swing.JTextField grade;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelStudentList;
    private javax.swing.JLabel jLabelforOutstandingStudentsInEachClass;
    private javax.swing.JList<String> jListForResultFilteringNumOfModules;
    private javax.swing.JPanel jPanelForChoosingNumOfModules;
    private javax.swing.JPanel jPanelForResultByFilteringModule;
    private javax.swing.JPanel jPanelForTopStudentTable;
    private javax.swing.JPanel jPanelStudentPerfomanceForEachModule;
    private javax.swing.JProgressBar jProgressBarForFilteringModule;
    private javax.swing.JScrollPane jScrollPaneForModulePerformanceRank;
    private javax.swing.JScrollPane jScrollPaneForResult;
    private javax.swing.JScrollPane jScrollPaneForTopStudentInEachClass;
    private javax.swing.JScrollPane jScrollPaneResultOfFilteringNumOfModules;
    private javax.swing.JSplitPane jSplitPaneForSearchByFilteringNumofMod;
    private javax.swing.JTabbedPane jTabbedPaneForStudentAndModuleInfo;
    private javax.swing.JTextArea jTextAreaShowingModulePerformanceRank;
    private javax.swing.JToggleButton jToggleButtonSearch;
    private javax.swing.JLabel labelForClassNo;
    private javax.swing.JLabel labelForCredit;
    private javax.swing.JLabel labelForGPA;
    private javax.swing.JLabel labelForGrade;
    private javax.swing.JLabel labelForModCode;
    private javax.swing.JLabel labelForModName;
    private javax.swing.JTextField marks;
    private javax.swing.JTextField modCode;
    private javax.swing.JTextField modName;
    private javax.swing.JTextField name;
    private java.awt.Button studentInfoNEXTButton;
    private java.awt.Button studentInfoPREVButton;
    private java.awt.Button studentModuleNEXTButton;
    private java.awt.Button studentModulePREVbutton;
    private javax.swing.JTextField totalModulesLabel;
    private javax.swing.JTextField totalStudentsLabel;
    // End of variables declaration//GEN-END:variables
}
